# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/c210-common/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/libmediayamahaservice.so:obj/lib/libmediayamahaservice.so \
    vendor/samsung/c210-common/proprietary/libTVOut.so:obj/lib/libTVOut.so \
    vendor/samsung/c210-common/proprietary/libfimc.so:obj/lib/libfimc.so

# AUDIO
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/c210-common/proprietary/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/samsung/c210-common/proprietary/audio.primary.exynos4.so:system/lib/hw/audio.primary.exynos4.so \
    vendor/samsung/c210-common/proprietary/audio_policy.exynos4.so:system/lib/hw/audio_policy.exynos4.so \
    vendor/samsung/c210-common/proprietary/lib_Samsung_Acoustic_Module_Llite.so:system/lib/lib_Samsung_Acoustic_Module_Llite.so \
    vendor/samsung/c210-common/proprietary/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/c210-common/proprietary/lib_Samsung_Sound_Booster.so:system/lib/lib_Samsung_Sound_Booster.so \
    vendor/samsung/c210-common/proprietary/libasound.so:system/lib/libasound.so \
    vendor/samsung/c210-common/proprietary/liblvvefs.so:system/lib/liblvvefs.so \
    vendor/samsung/c210-common/proprietary/libmediayamaha.so:system/lib/libmediayamaha.so \
    vendor/samsung/c210-common/proprietary/libmediayamaha_jni.so:system/lib/libmediayamaha_jni.so \
    vendor/samsung/c210-common/proprietary/libmediayamaha_tuning_jni.so:system/lib/libmediayamaha_tuning_jni.so \
    vendor/samsung/c210-common/proprietary/libmediayamahaservice.so:system/lib/libmediayamahaservice.so \
    vendor/samsung/c210-common/proprietary/libsamsungAcousticeq.so:system/lib/libsamsungAcousticeq.so \
    vendor/samsung/c210-common/proprietary/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/c210-common/proprietary/libyamahasrc.so:system/lib/libyamahasrc.so \
    vendor/samsung/c210-common/proprietary/LVVEFS_Rx_Configuration.txt:system/etc/audio/LVVEFS_Rx_Configuration.txt \
    vendor/samsung/c210-common/proprietary/LVVEFS_Tx_Configuration.txt:system/etc/audio/LVVEFS_Tx_Configuration.txt \
    vendor/samsung/c210-common/proprietary/Rx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Rx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Rx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Tx_ControlParams_EARPIECE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_EARPIECE_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Tx_ControlParams_SPEAKER_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_SPEAKER_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADPHONE_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt:system/etc/audio/Tx_ControlParams_WIRED_HEADSET_WIDEBAND.txt \
    vendor/samsung/c210-common/proprietary/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/c210-common/proprietary/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/samsung/c210-common/proprietary/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
    vendor/samsung/c210-common/proprietary/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/samsung/c210-common/proprietary/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/samsung/c210-common/proprietary/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
    vendor/samsung/c210-common/proprietary/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/samsung/c210-common/proprietary/front.conf:system/usr/share/alsa/pcm/front.conf \
    vendor/samsung/c210-common/proprietary/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
    vendor/samsung/c210-common/proprietary/modem.conf:system/usr/share/alsa/pcm/modem.conf \
    vendor/samsung/c210-common/proprietary/rear.conf:system/usr/share/alsa/pcm/rear.conf \
    vendor/samsung/c210-common/proprietary/side.conf:system/usr/share/alsa/pcm/side.conf \
    vendor/samsung/c210-common/proprietary/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
    vendor/samsung/c210-common/proprietary/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
    vendor/samsung/c210-common/proprietary/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
    vendor/samsung/c210-common/proprietary/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
    vendor/samsung/c210-common/proprietary/surround71.conf:system/usr/share/alsa/pcm/surround71.conf

# EGL
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/gralloc.exynos4.so:system/lib/hw/gralloc.exynos4.so \
    vendor/samsung/c210-common/proprietary/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/c210-common/proprietary/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/c210-common/proprietary/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/c210-common/proprietary/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/c210-common/proprietary/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/c210-common/proprietary/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/c210-common/proprietary/libMali.so:system/lib/libMali.so \
    vendor/samsung/c210-common/proprietary/libUMP.so:system/lib/libUMP.so

# HWCOMPOSER
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/hwcomposer.exynos4.so:system/lib/hw/hwcomposer.exynos4.so \
    vendor/samsung/c210-common/proprietary/bintvoutservice:system/bin/bintvoutservice \
    vendor/samsung/c210-common/proprietary/libcec.so:system/lib/libcec.so \
    vendor/samsung/c210-common/proprietary/libddc.so:system/lib/libddc.so \
    vendor/samsung/c210-common/proprietary/libedid.so:system/lib/libedid.so \
    vendor/samsung/c210-common/proprietary/libfimc.so:system/lib/libfimc.so \
    vendor/samsung/c210-common/proprietary/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/c210-common/proprietary/libhdmiclient.so:system/lib/libhdmiclient.so \
    vendor/samsung/c210-common/proprietary/libTVOut.so:system/lib/libTVOut.so \
    vendor/samsung/c210-common/proprietary/libtvout_jni.so:system/lib/libtvout_jni.so \
    vendor/samsung/c210-common/proprietary/libtvoutinterface.so:system/lib/libtvoutinterface.so \
    vendor/samsung/c210-common/proprietary/libtvoutservice.so:system/lib/libtvoutservice.so

# SENSORS
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/sensors.exynos4.so:system/lib/hw/sensors.exynos4.so \
    vendor/samsung/c210-common/proprietary/libakm.so:system/lib/libakm.so \
    vendor/samsung/c210-common/proprietary/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/c210-common/proprietary/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/samsung/c210-common/proprietary/libmpl.so:system/lib/libmpl.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/gps.exynos4.so:system/lib/hw/gps.exynos4.so \
    vendor/samsung/c210-common/proprietary/gpsd:system/bin/gpsd \
    vendor/samsung/c210-common/proprietary/gps.cer:system/bin/gps.cer \
    vendor/samsung/c210-common/proprietary/gps.xml:system/etc/gps.xml

# LPM
PRODUCT_COPY_FILES += \
    vendor/samsung/c210-common/proprietary/charging_mode:system/bin/charging_mode \
    vendor/samsung/c210-common/proprietary/immvibed:system/bin/immvibed \
    vendor/samsung/c210-common/proprietary/playlpm:system/bin/playlpm \
    vendor/samsung/c210-common/proprietary/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/c210-common/proprietary/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_0.qmg:system/media/battery_charging_0.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/c210-common/proprietary/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/c210-common/proprietary/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/c210-common/proprietary/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/c210-common/proprietary/Disconnected.qmg:system/media/Disconnected.qmg

